import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Progress } from "./ui/progress";
import { Separator } from "./ui/separator";
import { CheckCircle, AlertCircle, TrendingUp, Clock, RefreshCw, Home } from "lucide-react";

interface Response {
  questionId: number;
  answer: string;
  timeSpent: number;
}

interface ResultsPageProps {
  responses: Response[];
  onRetakeInterview: () => void;
  onBackToHome: () => void;
}

interface AnalysisResult {
  overallScore: number;
  strengths: string[];
  improvements: string[];
  categoryScores: { category: string; score: number; feedback: string }[];
  totalTime: number;
  averageResponseTime: number;
}

const mockQuestions = [
  { id: 1, category: "Problem Solving", type: "behavioral" },
  { id: 2, category: "Technical Skills", type: "technical" },
  { id: 3, category: "Teamwork", type: "behavioral" },
  { id: 4, category: "Leadership", type: "situational" },
  { id: 5, category: "Growth Mindset", type: "behavioral" }
];

export function ResultsPage({ responses, onRetakeInterview, onBackToHome }: ResultsPageProps) {
  // Mock AI analysis - in a real app, this would be generated by AI
  const generateAnalysis = (): AnalysisResult => {
    const totalTime = responses.reduce((sum, r) => sum + r.timeSpent, 0);
    const averageResponseTime = totalTime / responses.length;
    
    // Mock scoring based on response length and time
    const categoryScores = mockQuestions.map(q => {
      const response = responses.find(r => r.questionId === q.id);
      const responseLength = response?.answer.length || 0;
      const timeSpent = response?.timeSpent || 0;
      
      // Simple scoring algorithm for demo
      let score = Math.min(95, Math.max(40, (responseLength / 10) + (timeSpent > 30 ? 20 : 10)));
      
      const feedback = score >= 80 ? "Excellent detailed response with clear examples" :
                      score >= 65 ? "Good response but could use more specific examples" :
                      "Response needs more detail and concrete examples";
      
      return {
        category: q.category,
        score: Math.round(score),
        feedback
      };
    });

    const overallScore = Math.round(categoryScores.reduce((sum, cs) => sum + cs.score, 0) / categoryScores.length);

    return {
      overallScore,
      categoryScores,
      totalTime,
      averageResponseTime: Math.round(averageResponseTime),
      strengths: [
        "Clear communication style",
        "Structured approach to problem-solving",
        "Good use of specific examples"
      ],
      improvements: [
        "Consider using more quantifiable results",
        "Expand on leadership experiences",
        "Include more technical depth in responses"
      ]
    };
  };

  const analysis = generateAnalysis();

  const getScoreColor = (score: number) => {
    if (score >= 80) return "text-green-600";
    if (score >= 65) return "text-yellow-600";
    return "text-red-600";
  };

  const getScoreBadgeVariant = (score: number) => {
    if (score >= 80) return "default";
    if (score >= 65) return "secondary";
    return "destructive";
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8">
      <div className="container mx-auto px-4 max-w-6xl">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold mb-2">Interview Results</h1>
          <p className="text-muted-foreground">
            Here's your comprehensive interview analysis and feedback
          </p>
        </div>

        {/* Overall Score Card */}
        <Card className="mb-8">
          <CardHeader className="text-center">
            <CardTitle className="flex items-center justify-center gap-3">
              <CheckCircle className="h-8 w-8 text-green-600" />
              Interview Complete
            </CardTitle>
            <CardDescription>Overall Performance Score</CardDescription>
          </CardHeader>
          <CardContent className="text-center">
            <div className="text-6xl font-bold mb-4 text-primary">
              {analysis.overallScore}
              <span className="text-2xl text-muted-foreground">/100</span>
            </div>
            <Badge variant={getScoreBadgeVariant(analysis.overallScore)} className="text-lg px-4 py-2">
              {analysis.overallScore >= 80 ? "Excellent" : 
               analysis.overallScore >= 65 ? "Good" : "Needs Improvement"}
            </Badge>
            <div className="mt-6 grid grid-cols-2 gap-4 text-sm">
              <div className="flex items-center justify-center gap-2">
                <Clock className="h-4 w-4" />
                <span>Total Time: {Math.floor(analysis.totalTime / 60)}m {analysis.totalTime % 60}s</span>
              </div>
              <div className="flex items-center justify-center gap-2">
                <TrendingUp className="h-4 w-4" />
                <span>Avg Response: {analysis.averageResponseTime}s</span>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="grid lg:grid-cols-2 gap-8 mb-8">
          {/* Category Breakdown */}
          <Card>
            <CardHeader>
              <CardTitle>Performance by Category</CardTitle>
              <CardDescription>Detailed breakdown of your interview performance</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {analysis.categoryScores.map((category, index) => (
                <div key={index}>
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-medium">{category.category}</span>
                    <Badge variant={getScoreBadgeVariant(category.score)}>
                      {category.score}%
                    </Badge>
                  </div>
                  <Progress value={category.score} className="h-2 mb-2" />
                  <p className="text-sm text-muted-foreground">{category.feedback}</p>
                </div>
              ))}
            </CardContent>
          </Card>

          {/* Strengths & Improvements */}
          <div className="space-y-8">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <CheckCircle className="h-5 w-5 text-green-600" />
                  Key Strengths
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {analysis.strengths.map((strength, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <CheckCircle className="h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" />
                      <span className="text-sm">{strength}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <AlertCircle className="h-5 w-5 text-orange-600" />
                  Areas for Improvement
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {analysis.improvements.map((improvement, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <AlertCircle className="h-4 w-4 text-orange-600 mt-0.5 flex-shrink-0" />
                      <span className="text-sm">{improvement}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Detailed Responses */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Your Responses</CardTitle>
            <CardDescription>Review your answers and our analysis</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {responses.map((response, index) => {
              const question = mockQuestions.find(q => q.questionId === response.questionId);
              const categoryScore = analysis.categoryScores.find(cs => cs.category === question?.category);
              
              return (
                <div key={response.questionId}>
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-3">
                      <Badge variant="outline">Question {index + 1}</Badge>
                      <span className="font-medium">{question?.category}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Clock className="h-4 w-4 text-muted-foreground" />
                      <span className="text-sm text-muted-foreground">{response.timeSpent}s</span>
                      <Badge variant={getScoreBadgeVariant(categoryScore?.score || 0)}>
                        {categoryScore?.score}%
                      </Badge>
                    </div>
                  </div>
                  <div className="bg-muted p-4 rounded-lg">
                    <p className="text-sm">{response.answer}</p>
                  </div>
                  {index < responses.length - 1 && <Separator className="mt-6" />}
                </div>
              );
            })}
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button onClick={onRetakeInterview} variant="outline" className="flex items-center gap-2">
            <RefreshCw className="h-4 w-4" />
            Retake Interview
          </Button>
          <Button onClick={onBackToHome} className="flex items-center gap-2">
            <Home className="h-4 w-4" />
            Back to Home
          </Button>
        </div>
      </div>
    </div>
  );
}